[package]
name = "videotest"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
glib = "0.20.7"
gstreamer = "0.23.4"
gstreamer-app = "0.23.4"
gstreamer-video = "0.23.4"
rfd = "0.15.1"
